version: '3.6'
services:
  telegraf:
    image: telegraf:1.15-alpine
    public: true
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
    - 8125/udp

  influxdb:
    image: influxdb:1.8-alpine
    public: true
    env_file: configuration.env
    ports:
      - 8086
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    env_file: configuration.env
    ports:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: {}
  influxdb_data: {}
