version: '3.6'
services:
  telegraf:
    image: telegraf:1.15-alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
    - '192.168.18.77:8125:8125/udp'
    depends_on:
      - influxdb
    networks:
      - kb-backend

  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - 8086
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - kb-backend

  grafana:
    image: grafana/grafana:latest
    env_file: configuration.env
    ports:
      - '192.168.18.77:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - kb-backend

volumes:
  grafana_data: {}
  influxdb_data: {}


networks:
  kb-backend:
    external: false
    name: kb-backend
